#!/usr/bin/env node
// Generate the per-page social-preview tags for the manual.
//
//   node apply-og.js site
//
// Each manual page already carries a <title> and a <meta name="description">
// written for it, so the OG tags are derived from those rather than invented
// here — there is one source for the page's own description, not two that can
// disagree.
//
// This exists because manual chapters are written by copying an existing page
// as a skeleton. Hand-written OG tags would come along with the copy, and a
// new chapter would quietly claim to be "The canvas" at the previous page's
// URL — wrong in exactly the place nobody looks, since the tags are invisible
// until someone shares the link. Re-running this fixes every page at once.
//
// Idempotent: the block is delimited by markers and replaced in place. The
// landing page is deliberately NOT touched — its tags are hand-tuned and
// describe the site rather than a chapter.

const fs = require('fs');
const path = require('path');

const SITE = 'https://clew-app.com';
const CARD = `${SITE}/images/clew-og-card.jpg`;
const CARD_ALT = "The Clew icon, a ball of purple yarn, beside the word Clew and the line 'A thread through your notes'.";

const BEGIN = '<!-- og:begin — generated by apply-og.js; edit the <title> and description above instead -->';
const END = '<!-- og:end -->';

const root = path.resolve(process.argv[2] || 'site');
const manualDir = path.join(root, 'manual');

// Attribute values are wrapped in double quotes, so a double quote in the
// source would end the attribute early. Everything else is already
// entity-encoded in the page it came from and is reused verbatim.
const attr = (s) => s.replace(/"/g, '&quot;');

function tagsFor({ title, description, url }) {
	return [
		BEGIN,
		`<link rel="canonical" href="${url}">`,
		`<meta property="og:title" content="${attr(title)}">`,
		`<meta property="og:description" content="${attr(description)}">`,
		'<meta property="og:type" content="article">',
		`<meta property="og:url" content="${url}">`,
		'<meta property="og:site_name" content="Clew">',
		'<meta property="og:locale" content="en_GB">',
		`<meta property="og:image" content="${CARD}">`,
		'<meta property="og:image:width" content="1200">',
		'<meta property="og:image:height" content="630">',
		'<meta property="og:image:type" content="image/jpeg">',
		`<meta property="og:image:alt" content="${attr(CARD_ALT)}">`,
		'<meta name="twitter:card" content="summary_large_image">',
		`<meta name="twitter:title" content="${attr(title)}">`,
		`<meta name="twitter:description" content="${attr(description)}">`,
		`<meta name="twitter:image" content="${CARD}">`,
		`<meta name="twitter:image:alt" content="${attr(CARD_ALT)}">`,
		END,
	].join('\n');
}

const pages = fs.readdirSync(manualDir).filter((f) => f.endsWith('.html')).sort();
let written = 0;
const skipped = [];

for (const file of pages) {
	const full = path.join(manualDir, file);
	let html = fs.readFileSync(full, 'utf8');

	const title = html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim();
	const descMatch = html.match(/<meta\s+name="description"\s+content="([^"]*)"\s*\/?>/i);
	if (!title || !descMatch) {
		skipped.push(`${file} (no ${!title ? '<title>' : 'meta description'})`);
		continue;
	}

	// index.html is the manual's front door and lives at manual/, not
	// manual/index.html — the two would otherwise be a duplicate pair.
	const url = file === 'index.html' ? `${SITE}/manual/` : `${SITE}/manual/${file}`;
	const block = tagsFor({ title, description: descMatch[1], url });

	const existing = new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END}`);
	const next = existing.test(html)
		? html.replace(existing, block)
		: html.replace(descMatch[0], `${descMatch[0]}\n${block}`);

	if (next !== html) {
		fs.writeFileSync(full, next);
		written++;
	}
}

console.log(`${pages.length} manual pages, ${written} updated.`);
if (skipped.length) {
	console.log('\nSkipped:');
	for (const s of skipped) console.log(`  ${s}`);
	process.exitCode = 1;
}
